name: "\U0001F41E Report a problem"
description: "Report an issue with Phalcon"
title: "Bug: (fill in)"
labels: 
  - bug
body:
- type: input
  id: txhash
  attributes:
    label: Transaction Hash
  validations:
    required: true
- type: dropdown
  id: chain
  attributes:
    label: Chain
    multiple: false
    options:
      - Ethereum
      - Binance Smart Chain
      - Cronos
      - Avalanche-C
      - Polygon
      - Arbitrum
  validations:
    required: true
- type: textarea
  attributes:
    label: What did you expect to happen?
    description: |
      You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: What actually happened?
    description: |
      You can use Markdown in this field.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional comments
    description: Is there anything else that's important for the team to know?

